//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace leeyi45.acmun.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:01:30")]
        public global::System.TimeSpan GSLSpeakTime {
            get {
                return ((global::System.TimeSpan)(this["GSLSpeakTime"]));
            }
            set {
                this["GSLSpeakTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Maj50Plus1 {
            get {
                return ((bool)(this["Maj50Plus1"]));
            }
            set {
                this["Maj50Plus1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Maj67Plus1 {
            get {
                return ((bool)(this["Maj67Plus1"]));
            }
            set {
                this["Maj67Plus1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan UnmodSpeakTime {
            get {
                return ((global::System.TimeSpan)(this["UnmodSpeakTime"]));
            }
            set {
                this["UnmodSpeakTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:01:00")]
        public global::System.TimeSpan ModSpeakTime {
            get {
                return ((global::System.TimeSpan)(this["ModSpeakTime"]));
            }
            set {
                this["ModSpeakTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:10:00")]
        public global::System.TimeSpan ModSpeakTotal {
            get {
                return ((global::System.TimeSpan)(this["ModSpeakTotal"]));
            }
            set {
                this["ModSpeakTotal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:01:00")]
        public global::System.TimeSpan UnmodSummaryTime {
            get {
                return ((global::System.TimeSpan)(this["UnmodSummaryTime"]));
            }
            set {
                this["UnmodSummaryTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveSpeakTime {
            get {
                return ((bool)(this["SaveSpeakTime"]));
            }
            set {
                this["SaveSpeakTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveMotions {
            get {
                return ((bool)(this["SaveMotions"]));
            }
            set {
                this["SaveMotions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TrackDebate {
            get {
                return ((bool)(this["TrackDebate"]));
            }
            set {
                this["TrackDebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DebateSpeakCount {
            get {
                return ((int)(this["DebateSpeakCount"]));
            }
            set {
                this["DebateSpeakCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:01:30")]
        public global::System.TimeSpan DebateSpeakTime {
            get {
                return ((global::System.TimeSpan)(this["DebateSpeakTime"]));
            }
            set {
                this["DebateSpeakTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:03:00")]
        public global::System.TimeSpan ResoReadTime {
            get {
                return ((global::System.TimeSpan)(this["ResoReadTime"]));
            }
            set {
                this["ResoReadTime"] = value;
            }
        }
    }
}
